/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as LogoutRouteImport } from './routes/logout';
import { Route as ChatRouteImport } from './routes/chat';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as UIdRouteImport } from './routes/u.$id';
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const LogoutRoute = LogoutRouteImport.update({
    id: '/logout',
    path: '/logout',
    getParentRoute: () => rootRouteImport,
});
const ChatRoute = ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const UIdRoute = UIdRouteImport.update({
    id: '/u/$id',
    path: '/u/$id',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    ChatRoute: ChatRoute,
    LogoutRoute: LogoutRoute,
    ProfileRoute: ProfileRoute,
    UIdRoute: UIdRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
